#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Motor,  port1,           leftRear,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightIntake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rightArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           leftArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           leftArm,       tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightRear,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////


void pre_auton()
{

  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

        // All activities that occur before the competition starts
        // Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

 task autonomous()
{
        //Hits first friendly large ball into goal zone. (Total time: 1 second)
  while (true)
        {


motor[leftFront] = 127;
  motor[leftRear] = 127;
  motor[rightFront] = 127;
  motor[rightRear] = 127;
wait1Msec(1000) ;
  motor[leftFront] = 0;
  motor[leftRear] = 0;
  motor[rightFront] = 0;
  motor[rightRear] = 0;
  //Pushes buckey ball out
  				motor[leftIntake] = 127;
  				motor[rightIntake] = 127;

 wait1Msec(500);
  motor[leftIntake] = 0;
  motor[rightIntake] = 0;
  motor[leftFront] = -127;
  motor[leftRear] = -127;
  motor[rightFront] = -127;
  motor[rightRear] = -127;
 wait10Msec(1000);
    motor[leftFront] = 0;
  motor[leftRear] = 0;
  motor[rightFront] = 0;
  motor[rightRear] = 0;


wait10Msec(30);//Hits first friendly large ball into goal zone. (Total time: 1 second)
	motor[leftArm] = 80;
  motor[rightArm] = 80;
wait10Msec(100);
  motor[rightArm]= 0;
  motor[leftArm] = 0;
  motor[leftFront] = 127;
  motor[leftRear] = 127;
  motor[rightFront] = 127;
  motor[rightRear] = 127;
wait10Msec(300);
  motor[leftFront] = 0;
  motor[leftRear] = 0;
  motor[rightFront] = 0;
  motor[rightRear] = 0;
  motor[rightArm] = -80;
  motor[leftArm] = -80;
}
  }




        /////////////////////////////////////////////////////////////////////////////////////////
//

//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
	{        while (true)
        {

          // This is the main execution loop for the user control program. Each time through the loop
          // your program should update motor + servo values based on feedback from the joysticks.

          // .....................................................................................
          // Insert user code here. This is where you use the joystick values to update your motors, etc.
          // .....................................................................................

                //Arm
          //Use Left Stick




                if (vexRT[Btn6U] == 1)
                {
                        motor[leftIntake] = 127;
                        motor[rightIntake] = 127;
                }
                else if (vexRT[Btn6D] == 1)
                {
                        motor[leftIntake] = -127;
                        motor[rightIntake] = -127;
                }
                else
                {
                        motor[leftIntake] = 0;
                        motor[rightIntake] = 0;
                }
                //arm up and down Channel 3
                motor[leftArm] = vexRT[Ch3];
                motor[rightArm] = vexRT[Ch3];
                //Turning/Straight driving
                //Use Right-Stick


                        motor[rightFront] = (vexRT[Ch2] + vexRT[Ch1]);
                        motor[rightRear] = (vexRT[Ch2] + vexRT[Ch1]);
                        motor[leftRear] = (vexRT[Ch2] - vexRT[Ch1]);
                        motor[leftFront]= (vexRT[Ch2] - vexRT[Ch1]);
               }
}
