#pragma config(Sensor, dgtl12, touchSensor,    sensorDigitalIn)
#pragma config(Motor,  port1,           leftFront,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rightIntake,   tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftArm,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           rightArm,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftArm2,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightArm2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           leftRear,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightRear,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void driveSpeed(int x)
	{
		motor[leftFront] = x;
    motor[leftRear] = x;
    motor[rightFront] = x;
    motor[rightRear] = x;
	}
void armLift(int x)
	{
		motor[leftArm] = x;
		motor[rightArm] = x;
    motor[leftArm2] = x;
    motor[rightArm2] = x;
 }
 void intake (int x)
 {
   motor[leftIntake] = x;
   motor[rightIntake] = x;
 }
 void turn (int x, int y)
 {
   motor[leftFront] = x;
   motor[leftRear] = x;
   motor[rightFront] = y;
   motor[rightRear] = y;
 }
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

        // All activities that occur before the competition starts
        // Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  //if (SensorValue(touchSensor) == 0)
  //{
        //Hits first friendly large ball into goal zone. (Total time: 1 second)
bool outside=true;//set to false if behind bump,set to true if doing autonomous infront
        if(outside == true)
                {
                ClearTimer(T1);
        while(time1[T1] < 1000)
        {
          driveSpeed(80);
          armLift(70);
        }
          driveSpeed(0);
                //uh...intake... (Total time: 3 seconds)
        ClearTimer(T1);
        while(time1[T1] < 2000)
        {
           intake(127);
        }
                //outtake (Total time: 5 seconds)
        ClearTimer(T1);
        while(time1[T1] < 2000)
        {
           intake(-127);
        }
        //Go back with arm up. (Total time: 5.9 seconds)
        ClearTimer(T1);
        while(time1[T1] < 900)
        {
          driveSpeed(-100);
          armLift(10);
        }
        //Wait for three seconds and point robot in the direction of next ball. (Total time: 8.9 seconds)
        ClearTimer(T1);
        while(time1[T1] < 3000)
        {
          driveSpeed(0);
          armLift(10);
          intake(0);
        }
        //Lowers arm. (Total time: 9.1 seconds)
        ClearTimer(T1);
        while(time1[T1] < 200)
        {
          armLift(-70);
        }

        //Go forward for two seconds, and lifts arm. (Total time: 11.3 seconds)
                ClearTimer(T1);
        while(time1[T1] < 2200)
        {
  driveSpeed(80);
  armLift(30);
        }
        //Timeout
        driveSpeed(0);
    armLift(0);
  intake(0);
}

else //if behind bump (inside)
{
        //raise arm (Total time: 0.5 seconds)
          armLift(65);
        wait1Msec(500);
        //Intake?. (Total time: 1.5 seconds)
                intake(127);
        wait1Msec(1000);
        //Outtake. (Total time: 3.5 seconds)
                intake(-127);
        wait1Msec(2000);
        //Wait for two seconds (manually orient robot?) (Total time: 5.5 seconds)
                intake(0);
                wait1Msec(2000);
        //move forward and hit 3 buckyballs (this lowers the arm?) (Total time: 6.3 seconds)
              armLift(-22);
  wait1Msec(800);
  //Drive forwards and slightly lift arm. (Total time: 7.8 seconds)
          armLift(9);
          driveSpeed(80);
        wait1Msec(1500);
        //Timeout
          armLift(0);
               driveSpeed(0);
          intake(0);
}
/*15 point + enemy ball middle zone. Currently does not work, needs testing.
				//Hits first friendly large ball into goal zone. (Total time: 1 second)
 				ClearTimer(T1);
        while(time1[T1] < 1000)
        {
          driveSpeed(80);
          armLift(70);
        }
        //Keeps arm lifted, turns to the right 90 degrees. (Total time: 1.5 seconds)
        ClearTimer(T1);
        while(time1[T1] < 500)
        {
        turn(127,-127);
        }
        //Hits second friendly large ball into goal zone. (Total time: 2.5 seconds)
        ClearTimer(T1);
        while(time1[T1] < 1000)
        {
 driveSpeed(127);
        }
        //Lowers arm in prep for going under barrier, turns to the left 90 degrees. (Total time: 3 seconds)
        ClearTimer(T1);
        while(time1[T1] < 500)
        {
   turn(-127,127);
	armLift(-60);
        }
        //Moves up to the goal. (Total time: 4 seconds)
        ClearTimer(T1);
        while(time1[T1] < 1000)
        {
  driveSpeed(127);
        }
        //Lifts arm. (Total time: 5 seconds)
        ClearTimer(T1);
        while(time1[T1] < 1000)
        {
          armLift(60);
        }
        //Deposits preloads in goal. (Total time: 6.5 seconds)
        ClearTimer(T1);
        while(time1[T1] < 1500)
        {
           intake(-127);
        }
        //Turns to the right 120 degrees and lowers arm slightly. (Total time: 7 1/6 seconds)
        ClearTimer(T1);
        while(time1[T1] < 667)
        {
           turn(127,-127);
              armLift(-20);
        }
        //Hits enemy large ball into middle zone. (Total time: 8 2/3 seconds)
        ClearTimer(T1);
        while(time1[T1] < 1500)
        {
               driveSpeed(127);
        }
        //Turns to the left 60 degrees. (Total time: 9 seconds)
        ClearTimer(T1);
        while(time1[T1] < 333)
        {
           turn(-127,127);
        }
        //Hits other enemy large ball into middle zone. (Total time: 10 seconds)
        ClearTimer(T1);
        while(time1[T1] < 1000)
        {
             driveSpeed(127);
        }
        //Turns to the right 135 degrees and lowers arm. (Total time: 10.75 seconds)
        ClearTimer(T1);
        while(time1[T1] < 750)
        {
                armLift(-60);
                turn(127,-127);
        }
        //Travels as far as possible southwest while attempting to pick up more buckyballs. (Time out)
        ClearTimer(T1);
        while(time1[T1] < 4125)
        {
               intake(127);
                driveSpeed(127);
        }
*/

}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
        // User control code here, inside the loop
        while (true)
        {
          // This is the main execution loop for the user control program. Each time through the loop
          // your program should update motor + servo values based on feedback from the joysticks.

          // .....................................................................................
          // Insert user code here. This is where you use the joystick values to update your motors, etc.
          // .....................................................................................

         //Arm
          //Use Left Stick
                armLift(vexRT[Ch3]);

                //Intake
                //RB Upper is Intake, LB Upper is Output
                if (vexRT[Btn5U] == 1)
                {
                    intake(-127);
                }
                else if (vexRT[Btn6U] == 1)
                {
                   intake(127);
                }
                else
                {
                   intake(0);
                }
                //Turning/Straight driving
                //Use Right-Stick
                if((vexRT[Ch1] > 20) || (vexRT[Ch1] < -20))
                {
                        turn((vexRT[Ch2] + vexRT[Ch1]),(vexRT[Ch2] - vexRT[Ch1]));
                }
                else
                {
                        driveSpeed(vexRT[Ch2]);
                }
        }
}
