#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const string sAuton_DoNothing = "DO NOTHING";
const string sAuton_AutonomousMiddleZone =  "AUTO MID  ";
const string sAuton_AutonomousHangingZone = "AUTO HANG ";
const string sAuton_Skills    = "SKILLS";
const short lcd_kLeftBtn = 1;
const short lcd_kCenterBtn = 2;
const short lcd_kRightBtn = 4;
const short lcd_autonModeMID = 0;
const short lcd_autonModeHANG = 1;
int lcd_autonMode = 0;

void clearLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}

void batteryInfo() {
	string mainBattery, backupBattery;//, peBattery;
	//Display main battery voltage
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); // Build the value to be displayed
	string line1="M: ";
	strcat(line1,mainBattery);

	//Display Power Expander battery voltage
	/*int peBatteryLevel=SensorValue[powerexp];
	sprintf(peBattery, "%1.1f%c", peBatteryLevel/182.4,'V'); //Build the value to be displayed
	string line1Part2 = " E: ";
	strcat(line1Part2, peBattery);
	strcat(line1,line1Part2);
	displayLCDString(0,0,line1);*/

	//Display the Backup battery voltage
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    // Build the value to be displayed
	string line1p2=" B: ";
	strcat(line1, line1p2);
	strcat(line1,backupBattery);
	displayLCDString(0,0,line1);
}
int prevPress = 0;
void autonSelect() {
	if (nLCDButtons == prevPress) {
		return;
	}
	prevPress = nLCDButtons;
	string line2="A: ";
	if (nLCDButtons == lcd_kCenterBtn) {
			lcd_autonMode++;
			if (lcd_autonMode > 1) {
				lcd_autonMode = 0;
			}
	}
	string a = (lcd_autonMode == 0 ? sAuton_AutonomousMiddleZone : sAuton_AutonomousHangingZone);
	strcat(line2,a);
	displayLCDString(1,0,line2);
}

task LCDController() {
	clearLCD();
	while (true) {
		batteryInfo();
		autonSelect();
		wait1Msec(100);
	}
}
