#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, in4,    powerexp,       sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const string sAuton_DoNothing = "DO NOTHING";
const string sAuton_Universal = "AUTONOMOUS";
const string sAuton_Skills    = "SKILLS";
const short lcd_leftBtn = 1;
const short lcd_centerBtn = 2;
const short lcd_rightBtn = 4;
const short lcd_modeBattery = 0;
const short lcd_modeAutonomous = 1;

void displayString(string L1,string L2){
	string blank = "";
	if(L1!=blank || L2!=blank){
		string line1=L1;
		string line2=L2;
		displayLCDCenteredString(0,line1);
		displayLCDCenteredString(1,line2);
	}
}

void clearLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}

void batteryInfo() {
	string mainBattery, backupBattery, peBattery;
	//Display main battery voltage
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	string line1="M: ";
	strcat(line1,mainBattery);

	//Display Power Expander battery voltage
	int peBatteryLevel=SensorValue[powerexp];
	sprintf(peBattery, "%1.1f%c", peBatteryLevel/182.4,'V'); //Build the value to be displayed
	string line1Part2 = " E: ";
	strcat(line1Part2, peBattery);
	strcat(line1,line1Part2);
	displayLCDString(0,0,line1);

	//Display the Backup battery voltage
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
	string line2="Backup: ";
	strcat(line2,backupBattery);
	displayLCDString(1,0,line2);
}
void autonSelect() {

}
void initLCD() {

}
task LCDOverlord() {
	initLCD();
	while (true) {
		batteryInfo();
	}
}
