#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    accel,          sensorNone)
#pragma config(Sensor, in2,    poten,          sensorNone)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    powerexp,       sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           armRight,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           intakeRight,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armLeft2,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armLeft,       tmotorVex393, openLoop)
#pragma config(Motor,  port6,           backRight,     tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port7,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port10,          armRight2,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"
#include "PIDController.c"
#include "Sound.c"
#include "LCD.c"

PIDController armPID;
PIDController turnPID;

const int ARMAX = 3800;
const int ARMIN = 2000;
int autonomousChoice = 0;

void driveArcade(int y, int x) {
	motor[frontLeft] = motor[backLeft] = y + x;
	motor[frontRight] = motor[backRight] = y - x;
}
void setArmSpeed(int z) {
	motor[armRight] = motor[armLeft] = motor[armLeft2] = motor[armRight2] = z;
}
void setIntakeSpeed(int speed) {
		motor[intakeLeft] = motor[intakeRight] = speed;
}
int scaleInput(int a) {
	return a;
}

///////////////////////////////////////////////////////////
// Robot Tasks
///////////////////////////////////////////////////////////

void pre_auton() {
	init(armPID, 0.564444, 0, 0);
	init(turnPID, 0.267368, 0, 0);

	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	SensorValue[gyro]=0;
	SensorFullCount[gyro]=3600;

	StartTask(LCDOverlord);

	// Autonomous initialization
  bStopTasksBetweenModes = true;
}

task autonomous() {
	// Autonomous

	setIntakeSpeed(127);				//drop buckie ball

	setArmSpeed(100);
	wait1Msec(1000);
	setArmSpeed(5);

	driveArcade(70,0);					//drive forward
	wait1Msec(1100);
	driveArcade(0,0);

	setIntakeSpeed(0);
	setArmSpeed(20);

	wait1Msec(1000);

	driveArcade(-70,0);				//drive back
	wait1Msec(1200);
	driveArcade(0,0);

	wait1Msec(5000);

	driveArcade(70,0);					//drive forward
	wait1Msec(1300);
	driveArcade(0,0);

	wait1Msec(1000);

	driveArcade(-70,0);				//drive back
	wait1Msec(1300);
	driveArcade(0,0);
}

task usercontrol() {
	// User control initialization
	while (true) { // User control loop
	  int driveX = scaleInput(vexRT[Ch4]);
	  int driveY = scaleInput(vexRT[Ch3]);
	  int armSpeed = vexRT[Ch2];
	  int intakeSpeed = 127*((vexRT[Btn5U]|vexRT[Btn5D])-(vexRT[Btn6U]|vexRT[Btn6D]));
/*		string potenString, gyroString;
s		sprintf(potenString, "%3f%c", SensorValue[poten]);
		sprintf(gyroString, "%3f%c", SensorValue[gyro]);
		displayString(potenString, gyroString);*/

		if (SensorValue[poten] > ARMAX) armSpeed = 0; // Limit the Poten from dying.

		driveX = turnPID.enabled ? calculate(turnPID, SensorValue[gyro]) : driveX;
		armSpeed = armPID.enabled ? calculate(armPID, SensorValue[poten]) : armSpeed;

		if (abs(driveY) < 5) driveY = 0; // Deadband
		if (abs(driveX) < 5) driveX = 0;

	  driveArcade(driveY, driveX);
	  setArmSpeed(armSpeed);
	  setIntakeSpeed(intakeSpeed);
	}
}
