#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    accel,          sensorNone)
#pragma config(Sensor, in2,    poten,          sensorNone)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    powerexp,       sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           intakeRight,   tmotorVex393, openLoop)
#pragma config(Motor,  port2,           armRight,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           armRight2,     tmotorVex393, openLoop,reversed)
#pragma config(Motor,  port4,           armLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armLeft2,       tmotorVex393, openLoop)
#pragma config(Motor,  port6,           backRight,    tmotorVex393, openLoop,encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           frontRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           backLeft,     tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port9,           frontLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          intakeLeft,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"
#include "PIDController.c"
#include "Sound.c"

PIDController armPID;
PIDController turnPID;

const int ARMAX = 3800;
const int ARMIN = 2000;

void driveArcade(int y, int x) {
	motor[frontLeft] = motor[backLeft] = y + x;
	motor[frontRight] = motor[backRight] = y - x;
}
void setArmSpeed(int z) {
	motor[armRight] = motor[armLeft] = motor[armLeft2] = motor[armRight2] = z;
}
void setIntakeSpeed(int speed) {
		motor[intakeLeft] = motor[intakeRight] = speed;
}
int scaleInput(int a) {
	return a;
	//return a * a;
}



///////////////////////////////////////////////////////////
// Robot Tasks
///////////////////////////////////////////////////////////

void pre_auton() {
	init(armPID, 0.564444, 0, 0);
	init(turnPID, 0.267368, 0, 0);

	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	SensorValue[gyro]=0;
	SensorFullCount[gyro]=3600;

	// Autonomous initialization
  bStopTasksBetweenModes = true;

}
int setpoint;
task autonomous() {



}

task usercontrol() {
	// User control initialization
	while (true) { // User control loop
	  int driveX = scaleInput(vexRT[Ch4]);
	  int driveY = scaleInput(vexRT[Ch3]);
	  int armSpeed = vexRT[Ch2];
	  int intakeSpeed = 127*((vexRT[Btn5U]|vexRT[Btn5D])-(vexRT[Btn6U]|vexRT[Btn6D]));
	  if (vexRT[Btn8R] == 1) {
	  	if (armPID.enabled != true) {
	 			setSetpoint(armPID, SensorValue[poten]);
	 			setEnabled(armPID, true);
	 			setThresholds(armPID, -127, 127);
	 		} else {
	 			setEnabled(armPID, false);
	 		}
		}
	  if (vexRT[Btn8D] == 1) {
			if (turnPID.enabled == true) {
				setEnabled(turnPID, false);
			} else {
				setEnabled(turnPID, true);
				setSetpoint(turnPID, SensorValue[gyro]);
				setThresholds(turnPID, -127, 127);
			}
		}
/*		string potenString, gyroString;
		sprintf(potenString, "%3f%c", SensorValue[poten]);
		sprintf(gyroString, "%3f%c", SensorValue[gyro]);
		displayString(potenString, gyroString);*/

		if (SensorValue[poten] > ARMAX) armSpeed = 0; // Limit arm below physical threshold.

		driveX = turnPID.enabled ? calculate(turnPID, SensorValue[gyro]) : driveX;
		armSpeed = armPID.enabled ? calculate(armPID, SensorValue[poten]) : armSpeed;

		if (abs(driveY) < 5) driveY = 0; // Deadband
		if (abs(driveX) < 5) driveY = 0;

	  driveArcade(driveY, driveX);
	  setArmSpeed(armSpeed);
	  setIntakeSpeed(intakeSpeed);
	}
}
